### ISSUE TITLE
Erro de dependência: puppeteer e Chromium

### ISSUE THREAD

**Issue by ZehCoque** [Menighin/cei-crawler#53]
Opa! Tudo beleza? 

Primeiramente, meus **parabéns pelo excelente trabalho**! Facilitou a vida de muito dev por aí!

Estou tendo um problema e tenho razões para acreditar que não é minha máquina (até porque eu estou rodando as funções na nuvem).

> Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (901912).
    at ChromeLauncher.launch (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/Launcher.js:88:27)
    at async CeiLoginService._getTokenByUserResolve (/var/task/node_modules/cei-crawler/src/lib/CeiLoginService.js:36:25)
    at async CeiLoginService.getToken (/var/task/node_modules/cei-crawler/src/lib/CeiLoginService.js:26:24)
    at async CeiCrawler._login (/var/task/node_modules/cei-crawler/src/lib/CeiCrawler.js:67:29)
    at async CeiCrawler.getConsolidatedValues (/var/task/node_modules/cei-crawler/src/lib/CeiCrawler.js:77:9)

Já tentei instalar o `Chromium` e o `puppeteer` localmente e não funcionou. E de qualquer forma não pretendo usar essas funções localmente. O package precisa funcionar por si só. Tenho usado o `cei-crawler v2` sem problema.

### Muito obrigado!

**Comment by Menighin** [comment]
Olá @ZehCoque desculpe o atraso na resposta
Qual versao vc está usando? Como esta a configuracao?

**Comment by ZehCoque** [comment]
Vou fechar essa issue, eu consegui fazer funcionar. Acredito que na época que tentei, a documentação não estava completa e a package não pedia pelo browserPath.
